
<number>     ::= 0 | 1 | 2 | 3 | ... | 9
<addop>      ::= + | -
<mulop>      ::= * | /
<variable>   ::= a | b | c | ... | z | A | B | C | ... | Z
<factor>     ::= <number> | (<expression>) | <variable>
<term>       ::= <factor> [ <mulop> <factor> ]*
<expression> ::= <term> [ <addop> <term> ]*
