
<number>     ::= [0-9]
<addop>      ::= + | -
<mulop>      ::= * | /
<factor>     ::= <number> | (<expression>)
<term>       ::= <factor> [ <mulop> <factor> ]*
<expression> ::= <term> [ <addop> <term> ]*
