<program> ::= PROGRAM <top-level decl> <main> '.'
<main> ::= BEGIN <block> END
<top-level decls> ::= ( <data declaration> )*
<data declaration> ::= VAR <var-list>
<var-list> ::= <var> (, <var>)*
<var> ::= <ident> [ = <integer> ]
